#include "main.h"
#include <sys/types.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/wait.h>

/**
 * execute_command - execute the tokens generated by our split_input function.
 * @tokens: list of arguments passed to the program.
 * Return: Nothing.
 */

void execute_command(char **tokens)
{
	pid_t childpid;
	int status;

	childpid = fork();
	if (childpid < 0)
	{
		perror("Error");
		exit(1);
	}
	else if (childpid == 0)
	{
		if (execve(tokens[0], tokens, environ) == -1)
		{
			perror("Error");
		}
		exit(1);
		
	}
	else
	{
		wait(&status);
	}
}
